config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :courses
  
  root 'landingpage#show'
  
  #constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #  root to: "landingpage#show", as: :admin_root
  #end

  #constraints Clearance::Constraints::SignedIn.new do
  #  root to: "landingpage#show", as: :signed_in_root
  #end

  #constraints Clearance::Constraints::SignedOut.new do
  #  root to: "landingpage#show"
  #end

end

app/models/program_director.rb
class ProgramDirector < ApplicationRecord
end

app/models/programdirector.rb
class Programdirector < ApplicationRecord
    has_many :professors
    #belongs_to :users
    
    validates :Name, presence: true
    validates :CWID, presence: true
end

app/controllers/program_directors_controller.rb
class ProgramDirectorsController < ApplicationController
  before_action :set_program_director, only: %i[ show edit update destroy ]

  # GET /program_directors or /program_directors.json
  def index
    @program_directors = ProgramDirector.all
  end

  # GET /program_directors/1 or /program_directors/1.json
  def show
  end

  # GET /program_directors/new
  def new
    @program_director = ProgramDirector.new
  end

  # GET /program_directors/1/edit
  def edit
  end

  # POST /program_directors or /program_directors.json
  def create
    @program_director = ProgramDirector.new(program_director_params)

    respond_to do |format|
      if @program_director.save
        format.html { redirect_to @program_director, notice: "Program director was successfully created." }
        format.json { render :show, status: :created, location: @program_director }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @program_director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /program_directors/1 or /program_directors/1.json
  def update
    respond_to do |format|
      if @program_director.update(program_director_params)
        format.html { redirect_to @program_director, notice: "Program director was successfully updated." }
        format.json { render :show, status: :ok, location: @program_director }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @program_director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /program_directors/1 or /program_directors/1.json
  def destroy
    @program_director.destroy
    respond_to do |format|
      format.html { redirect_to program_directors_url, notice: "Program director was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program_director
      @program_director = ProgramDirector.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_director_params
      params.require(:program_director).permit(:Name, :Department)
    end
end

app/helpers/program_directors_helper.rb
module ProgramDirectorsHelper
end

app/views/programdirectors/index.html.erb
<html>
<head>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #1a3152;
  color: white;
}
</style>
</head>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
     <thead>
    <tr>
      <th>Name</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>
    </tr>
  </thead>

  <tbody>
    <% @professor.each do |professor| %>
      <tr>
        <td><%= professor.Name %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>


<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cwid</th>
      <th>Concentration</th>
      <th>Advisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student.each do |student| %>
      <tr>
        <td><%= student.Name %></td>
        <td><%= student.CWID %></td>
        <td><%= student.Concentration %></td>
        <td><%= student.Advisor %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

<h1>Courses</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Section</th>
      <th>Number</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>
  <% @course.each do |course| %>
   <tr>
       <td><%=course.prefix%></td>
       <td><%= link_to course.name, course %></td>
       <td><%=course.section%></td>
       <td><%=course.number%></td>
      <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>
<%= link_to "New Course", new_course_path %>