config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :courses
  
  root 'landingpage#show'
  
  #constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #  root to: "landingpage#show", as: :admin_root
  #end

  #constraints Clearance::Constraints::SignedIn.new do
  #  root to: "landingpage#show", as: :signed_in_root
  #end

  #constraints Clearance::Constraints::SignedOut.new do
  #  root to: "landingpage#show"
  #end

end

app/models/professor.rb
class Professor < ApplicationRecord
    has_many :students
    belongs_to :programdirector
    #belongs_to :users
    
    validates :Name, presence: true
    validates :CWID, presence: true
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[ show edit update destroy ]

  # GET /professors or /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1 or /professors/1.json
  def show
    @students = Student.find(params[:id])
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors or /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: "Professor was successfully created." }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1 or /professors/1.json
  def update
    @professor = Professor.find(params[:id])

    if @professor.update(professor_params)
      redirect_to @professor
    else
      render :edit
    end
  end

  # DELETE /professors/1 or /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: "Professor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professor_params
      params.require(:professor).permit(:Name)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :CWID %>
    <%= form.number_field :CWID %>
  </div>
  
   <div class="control-group">
    <%= form.label "Program Director", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:Programdirector, options_from_collection_for_select(Programdirector.all, 'Name', 'Name')) %>
    </div>
  </div>
  
   
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>
<html>
<head>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #1a3152;
  color: white;
}
</style>
</head>
<body>

<h1>Professors</h1>

<table>
  <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
</table>

</body>
</html>
<table>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.Name %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= button_to 'Destroy', professor_path(:id => professor), method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>

<html>
<head>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #1a3152;
  color: white;
}
</style>
</head>
<body>

<h1>Advisees</h1>

<table>
  <tr>
      <th colspan="3"></th>
    </tr>
</table>

</body>
</html>
<table>

<tbody>
    <% @professor.students.each do |student| %>
      <tr>
        <td><%= student.Name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>