config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :courses
  
  root 'landingpage#show'
  
  #constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #  root to: "landingpage#show", as: :admin_root
  #end

  #constraints Clearance::Constraints::SignedIn.new do
  #  root to: "landingpage#show", as: :signed_in_root
  #end

  #constraints Clearance::Constraints::SignedOut.new do
  #  root to: "landingpage#show"
  #end

end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :student
    has_many :semesters
    has_many :courses, through: :semesters
    
    validates :nameofplan, presence: true
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  belongs_to :students
  has_many :semesters
  
  # GET /plans or /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.fetch(:plan, {})
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #1a3152;
  color: white;
}
</style>
</head>
<body>

<h2><%= @plan.nameofplan %></h2>

<table>
  <tr>
    <th>Semester</th>
    <th>Course 1</th>
    <th>Course 2</th>
    <th>Course 3</th>
    <th>Course 4</th>
  </tr>
  <tr>
    <td><%= @plan.semester1  %></td>
    <td><%= @plan.course1a  %></td>
    <td><%= @plan.course1b  %></td>
    <td><%= @plan.course1c  %></td>
    <td><%= @plan.course1d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester2  %></td>
    <td><%= @plan.course2a  %></td>
    <td><%= @plan.course2b  %></td>
    <td><%= @plan.course2c  %></td>
    <td><%= @plan.course2d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester3  %></td>
    <td><%= @plan.course3a  %></td>
    <td><%= @plan.course3b  %></td>
    <td><%= @plan.course3c  %></td>
    <td><%= @plan.course3d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester4  %></td>
    <td><%= @plan.course4a  %></td>
    <td><%= @plan.course4b  %></td>
    <td><%= @plan.course4c  %></td>
    <td><%= @plan.course4d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester5  %></td>
    <td><%= @plan.course5a  %></td>
    <td><%= @plan.course5b  %></td>
    <td><%= @plan.course5c  %></td>
    <td><%= @plan.course5d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester6  %></td>
    <td><%= @plan.course6a  %></td>
    <td><%= @plan.course6b  %></td>
    <td><%= @plan.course6c  %></td>
    <td><%= @plan.course6d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester7  %></td>
    <td><%= @plan.course7a  %></td>
    <td><%= @plan.course7b  %></td>
    <td><%= @plan.course7c  %></td>
    <td><%= @plan.course7d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester8  %></td>
    <td><%= @plan.course8a  %></td>
    <td><%= @plan.course8b  %></td>
    <td><%= @plan.course8c  %></td>
    <td><%= @plan.course8d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester9  %></td>
    <td><%= @plan.course9a  %></td>
    <td><%= @plan.course9b  %></td>
    <td><%= @plan.course9c  %></td>
    <td><%= @plan.course9d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester10  %></td>
    <td><%= @plan.course10a  %></td>
    <td><%= @plan.course10b  %></td>
    <td><%= @plan.course10c  %></td>
    <td><%= @plan.course10d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester11  %></td>
    <td><%= @plan.course11a  %></td>
    <td><%= @plan.course11b  %></td>
    <td><%= @plan.course11c  %></td>
    <td><%= @plan.course11d  %></td>
  </tr>
  <tr>
    <td><%= @plan.semester12  %></td>
    <td><%= @plan.course12a  %></td>
    <td><%= @plan.course12b  %></td>
    <td><%= @plan.course12c  %></td>
    <td><%= @plan.course12d  %></td>
  </tr>
</table>

</body>
</html>