config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :courses
  
  root 'landingpage#show'
  
  #constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
  #  root to: "landingpage#show", as: :admin_root
  #end

  #constraints Clearance::Constraints::SignedIn.new do
  #  root to: "landingpage#show", as: :signed_in_root
  #end

  #constraints Clearance::Constraints::SignedOut.new do
  #  root to: "landingpage#show"
  #end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
   <!-- Sidebar -->
<div class="w3-sidebar w3-light-grey w3-bar-block" style="background-color: #1A3152!important; color:white;">
  <h3 class="w3-bar-item">iPOS</h3>
     <a href="<%= root_path  %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">HOME</a>
   <a href="<%= students_path  %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">STUDENTS</a>
 <a href="<%=professors_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">ADVISORS</a>
  <a href="<%= programdirectors_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">PROGRAM DIRECTORS</a>
  <a href="<%= comments_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">COMMENTS</a>
    <a href="<%= discussions_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">E-MAILS</a>
       <a href="<%= courses_path  %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #1a3152!important;">COURSES</a>
</div>
        <%= image_tag("CITADELLOGO.png",  :size => "200x40", :alt => "rss feed") %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <% if signed_in? %>
       
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
  <section>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
  </section>
    <%= yield %>
  </body>
</html>